name: Daily Action

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user (24ds3000028@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "24ds3000028@ds.study.iitm.ac.in"

      - name: Make a dummy commit
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt
          git commit -m "Automated commit: $(date)"
      
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main  # Change "main" if your branch is different
          
