name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Give write access to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user (24ds3000028@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "24ds3000028@ds.study.iitm.ac.in"

      - name: Make a dummy commit
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt
          git commit -m "Automated commit: $(date)"
          git push origin main
